apiVersion: apps/v1
kind: Deployment
metadata:
  name: vite-app-deployment
  labels:
    app: vite-app
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vite-app
  template:
    metadata:
      labels:
        app: vite-app
    spec:
      containers:
        - name: vite-app-container
          image: yuanxinc/vite-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: ENVIRONMENT
              value: "production"
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
